<?php
/**
 * @file
 * Hook implementations for OAuth module.
 */

/**
 * Implements hook_user_delete().
 */
function oauth_user_delete($account) {
  // Delete all tokens and consumers related to a user
  module_load_include('inc', 'oauth');

  $consumer_condition = db_select('oauth_provider_consumer', 'c')->condition('uid', $account->uid)->fields('c', array('csid'));
  $token_condition = db_or()->condition('uid', $account->uid)->condition('csid', $consumer_condition, 'IN');

  db_delete('oauth_provider_token')
    ->condition('tid', db_select('oauth_token', 't')->condition($token_condition)->fields('t', array('tid')), 'IN')
    ->execute();

  db_delete('oauth_token')
    ->condition($token_condition)
    ->execute();

  db_delete('oauth_consumer')
    ->condition('csid', $consumer_condition, 'IN')
    ->execute();

  db_delete('oauth_provider_consumer')
    ->condition('uid', $account->uid)
    ->execute();
}
